### ISSUE TITLE
Incorrect Arrow & Joint Behavior

### ISSUE THREAD

**Issue by fundamental** [christiangoltz/shaape#1]
When an arrow is used immediately before a joint, no connection is made between them.
An extra dash results in the expected behavior.

Example:

```
["shaape"]
-----------
->+------  
  |
  |
-----------
```

**Comment by christiangoltz** [comment]
Should be fixed with https://github.com/christiangoltz/shaape/commit/5aefa99fcc363828cdd291167248e100bbfd02e6
