### ISSUE TITLE
Setting defaults

### ISSUE THREAD

**Issue by ulim** [christiangoltz/shaape#2]
It would be great if one could change the defaults like background color, font color etc. E.g. when working with a black background one would probably reverse the defaults.

**Comment by christiangoltz** [comment]
There already is a possibilty to change the defaults, though it isn well documented yet. Please have a look at the ¨Advanced Example¨ in the Readme:

_default_: {fill:[[0, 1, 1]], frame:[[0.3, 0.3, 0.3, 1], dashed, 2], line:[red,dotted, 1], arrow:[[0.2, 0.7, 0.5, 0.7], flat]}

As you can see, you can already set the default fill for polygons, the default frame for polygons, the default line style and the default arrow style (which is the only possible way to set any arrow style at the moment).

If there is something specific missing(document background color, or text style in general), then you can create new feature request tickets for these, but in general this way for setting the defaults should work.

**Comment by christiangoltz** [comment]
default colors can be set by corresponding regex in current develop branch.
